engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
    exclude_paths:
      - "**/*.spec.js"
  eslint:
    enabled: true
    channel: "eslint-3"

ratings:
   paths:
     - "**.js"
